### ISSUE TITLE
Community EE (Execution Environments)

### ISSUE THREAD

**Issue by gundalow** [ansible-community/meetup#8]
### Talk idea/topic

Currently we don't have any Community Execution Environments. Lets get the discussion going about what they could look like

* What are EE (Execution Environments)
* What problems do they solve
* What do Product EE's look like
* What could Community EE's look like

**Comment by samccann** [comment]
Stumbled on this one and closing in favor of - https://github.com/ansible-community/community-team/issues/230  - which I think covers the new community EE in the works. Thanks!
